# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Connection_parameters(object):
    def setupUi(self, Connection_parameters):
        Connection_parameters.setObjectName("Connection_parameters")
        Connection_parameters.resize(361, 353)
        self.centralwidget = QtWidgets.QWidget(Connection_parameters)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 311, 271))
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_servo = QtWidgets.QLabel(self.widget)
        self.label_servo.setObjectName("label_servo")
        self.gridLayout.addWidget(self.label_servo, 0, 1, 1, 1)
        self.comboBox_linear = QtWidgets.QComboBox(self.widget)
        self.comboBox_linear.setObjectName("comboBox_linear")
        self.gridLayout.addWidget(self.comboBox_linear, 1, 0, 1, 1)
        self.comboBox_servo = QtWidgets.QComboBox(self.widget)
        self.comboBox_servo.setObjectName("comboBox_servo")
        self.gridLayout.addWidget(self.comboBox_servo, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_ens_ip = QtWidgets.QLabel(self.widget)
        self.label_ens_ip.setObjectName("label_ens_ip")
        self.gridLayout_2.addWidget(self.label_ens_ip, 0, 0, 1, 1)
        self.lineEdit_ens_IP = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ens_IP.setObjectName("lineEdit_ens_IP")
        self.gridLayout_2.addWidget(self.lineEdit_ens_IP, 0, 1, 1, 1)
        self.label_ens_port = QtWidgets.QLabel(self.widget)
        self.label_ens_port.setObjectName("label_ens_port")
        self.gridLayout_2.addWidget(self.label_ens_port, 1, 0, 1, 1)
        self.lineEdit_ens_port = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ens_port.setObjectName("lineEdit_ens_port")
        self.gridLayout_2.addWidget(self.lineEdit_ens_port, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.pushButton_check = QtWidgets.QPushButton(self.widget)
        self.pushButton_check.setObjectName("pushButton_check")
        self.gridLayout_4.addWidget(self.pushButton_check, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_error_servo = QtWidgets.QLabel(self.widget)
        self.label_error_servo.setText("")
        self.label_error_servo.setObjectName("label_error_servo")
        self.gridLayout_5.addWidget(self.label_error_servo, 1, 0, 1, 1)
        self.label_error_ensemble = QtWidgets.QLabel(self.widget)
        self.label_error_ensemble.setText("")
        self.label_error_ensemble.setObjectName("label_error_ensemble")
        self.gridLayout_5.addWidget(self.label_error_ensemble, 2, 0, 1, 1)
        self.label_error_linear = QtWidgets.QLabel(self.widget)
        self.label_error_linear.setText("")
        self.label_error_linear.setObjectName("label_error_linear")
        self.gridLayout_5.addWidget(self.label_error_linear, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        Connection_parameters.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Connection_parameters)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 22))
        self.menubar.setObjectName("menubar")
        Connection_parameters.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Connection_parameters)
        self.statusbar.setObjectName("statusbar")
        Connection_parameters.setStatusBar(self.statusbar)

        self.retranslateUi(Connection_parameters)
        QtCore.QMetaObject.connectSlotsByName(Connection_parameters)

    def retranslateUi(self, Connection_parameters):
        _translate = QtCore.QCoreApplication.translate
        Connection_parameters.setWindowTitle(_translate("Connection_parameters", "Connection parameters"))
        self.label.setText(_translate("Connection_parameters", "Linear stages port"))
        self.label_servo.setText(_translate("Connection_parameters", "Servo stage port"))
        self.label_ens_ip.setText(_translate("Connection_parameters", "Ensemble IP"))
        self.label_ens_port.setText(_translate("Connection_parameters", "Ensemble port"))
        self.pushButton_check.setText(_translate("Connection_parameters", "Connect"))
