# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'locked.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Unlocksystem(object):
    def setupUi(self, Unlocksystem):
        Unlocksystem.setObjectName("Unlocksystem")
        Unlocksystem.resize(426, 197)
        self.centralwidget = QtWidgets.QWidget(Unlocksystem)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 345, 97))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_homing = QtWidgets.QPushButton(self.widget, )
        self.pushButton_homing.setObjectName("pushButton_homing")
        self.gridLayout.addWidget(self.pushButton_homing, 0, 0, 1, 1)
        self.pushButton_override = QtWidgets.QPushButton(self.widget)
        self.pushButton_override.setObjectName("pushButton_override")
        self.gridLayout.addWidget(self.pushButton_override, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        Unlocksystem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Unlocksystem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 426, 22))
        self.menubar.setObjectName("menubar")
        Unlocksystem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Unlocksystem)
        self.statusbar.setObjectName("statusbar")
        Unlocksystem.setStatusBar(self.statusbar)

        self.retranslateUi(Unlocksystem)
        QtCore.QMetaObject.connectSlotsByName(Unlocksystem)

    def retranslateUi(self, Unlocksystem):
        _translate = QtCore.QCoreApplication.translate
        Unlocksystem.setWindowTitle(_translate("Unlocksystem", "Alarm state window"))
        self.label.setText(_translate("Unlocksystem", "The system entered alarm mode. \n"
" It is strongly adviced to execute a homing cycle."))
        self.pushButton_homing.setText(_translate("Unlocksystem", "Homing cycle"))
        self.pushButton_override.setText(_translate("Unlocksystem", "Override"))

    def openWindow(self):
        app = QtWidgets.QApplication(sys.argv)
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Unlocksystem()
        self.ui.setupUi(self.window)
        self.window.show()
        closeEvent()
        app.exec()

