# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Progress_window(object):
    def setupUi(self, Progress_window):
        Progress_window.setObjectName("Progress_window")
        Progress_window.resize(507, 321)
        self.centralwidget = QtWidgets.QWidget(Progress_window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start_scan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_scan.setGeometry(QtCore.QRect(210, 30, 83, 25))
        self.pushButton_start_scan.setObjectName("pushButton_start_scan")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 421, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout.addWidget(self.pushButton_cancel)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 130, 421, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_file_path = QtWidgets.QLabel(self.layoutWidget1)
        self.label_file_path.setObjectName("label_file_path")
        self.gridLayout.addWidget(self.label_file_path, 0, 0, 1, 2)
        self.label_angles_rotation = QtWidgets.QLabel(self.layoutWidget1)
        self.label_angles_rotation.setObjectName("label_angles_rotation")
        self.gridLayout.addWidget(self.label_angles_rotation, 1, 0, 1, 1)
        self.label_detector_position = QtWidgets.QLabel(self.layoutWidget1)
        self.label_detector_position.setObjectName("label_detector_position")
        self.gridLayout.addWidget(self.label_detector_position, 1, 1, 1, 1)
        self.label_object_position = QtWidgets.QLabel(self.layoutWidget1)
        self.label_object_position.setObjectName("label_object_position")
        self.gridLayout.addWidget(self.label_object_position, 2, 0, 1, 1)
        self.label_vertical_position = QtWidgets.QLabel(self.layoutWidget1)
        self.label_vertical_position.setObjectName("label_vertical_position")
        self.gridLayout.addWidget(self.label_vertical_position, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_magnification_ratio = QtWidgets.QLabel(self.layoutWidget1)
        self.label_magnification_ratio.setObjectName("label_magnification_ratio")
        self.gridLayout_2.addWidget(self.label_magnification_ratio, 1, 0, 1, 1)
        Progress_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Progress_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 22))
        self.menubar.setObjectName("menubar")
        Progress_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Progress_window)
        self.statusbar.setObjectName("statusbar")
        Progress_window.setStatusBar(self.statusbar)

        self.retranslateUi(Progress_window)
        QtCore.QMetaObject.connectSlotsByName(Progress_window)

    def retranslateUi(self, Progress_window):
        _translate = QtCore.QCoreApplication.translate
        Progress_window.setWindowTitle(_translate("Progress_window", "MainWindow"))
        self.pushButton_start_scan.setText(_translate("Progress_window", "Start Scan"))
        self.pushButton_cancel.setText(_translate("Progress_window", "Cancel"))
        self.label_file_path.setText(_translate("Progress_window", "File path:"))
        self.label_angles_rotation.setText(_translate("Progress_window", "Angles per rotation:"))
        self.label_detector_position.setText(_translate("Progress_window", "Detector position:"))
        self.label_object_position.setText(_translate("Progress_window", "Object position:"))
        self.label_vertical_position.setText(_translate("Progress_window", "Vertical position:"))
        self.label_magnification_ratio.setText(_translate("Progress_window", "Magnification ratio:"))
