# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Progress_window(object):
    def setupUi(self, Progress_window):
        Progress_window.setObjectName("Progress_window")
        Progress_window.resize(507, 198)
        self.centralwidget = QtWidgets.QWidget(Progress_window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start_scan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_scan.setGeometry(QtCore.QRect(210, 30, 83, 25))
        self.pushButton_start_scan.setObjectName("pushButton_start_scan")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 60, 421, 58))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout.addWidget(self.pushButton_cancel)
        Progress_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Progress_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 22))
        self.menubar.setObjectName("menubar")
        Progress_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Progress_window)
        self.statusbar.setObjectName("statusbar")
        Progress_window.setStatusBar(self.statusbar)

        self.retranslateUi(Progress_window)
        QtCore.QMetaObject.connectSlotsByName(Progress_window)

    def retranslateUi(self, Progress_window):
        _translate = QtCore.QCoreApplication.translate
        Progress_window.setWindowTitle(_translate("Progress_window", "MainWindow"))
        self.pushButton_start_scan.setText(_translate("Progress_window", "Start Scan"))
        self.pushButton_cancel.setText(_translate("Progress_window", "Cancel"))
